/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasfacebook;

import comVista.IComunicadorVista;
import entidades.Notificacion;
import entidades.Usuario;
import enumeradores.MotorEnvio;
import events.ConsultarUsuarioPorNombreEvent;
import events.RegistrarNotificacionEvent;
import interfaces.IConsultarUsuarioPorNombreObserver;
import interfaces.IRegistrarNotificacionObserver;
import java.util.Calendar;
import javax.swing.JOptionPane;
import peticiones.PeticionNotificacion;
import peticiones.PeticionUsuario;

/**
 * Frame para realizar mensaje privado
 * @author Jesus Valencia, Antonio del Pardo, Marco Irineo, Giovanni Garrido
 */
public class MensajePrivadoFrm extends javax.swing.JFrame implements IRegistrarNotificacionObserver, IConsultarUsuarioPorNombreObserver {
    /**
     * Comunicador de vista
     */
    private IComunicadorVista comunicadorVista;
    private Usuario usuario;

    /**
     * Creates new form FrmPublicacionPrueba
     *
     * @param comunicadorVista
     */
    public MensajePrivadoFrm(IComunicadorVista comunicadorVista) {
        initComponents();
        this.comunicadorVista = comunicadorVista;
        txtContenido.setLineWrap(true);
        RegistrarNotificacionEvent.getInstance().suscribirse(this);
        ConsultarUsuarioPorNombreEvent.getInstance().suscribirse(this);
    }

    public MensajePrivadoFrm(Usuario usuario, IComunicadorVista comunicadorVista) {
        initComponents();
        this.usuario = usuario;    
        this.comunicadorVista = comunicadorVista;
        RegistrarNotificacionEvent.getInstance().suscribirse(this);
        ConsultarUsuarioPorNombreEvent.getInstance().suscribirse(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        barra1 = new javax.swing.JLabel();
        barra2 = new javax.swing.JLabel();
        lblContenido = new javax.swing.JLabel();
        btnEnviarMensajePrivado = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        lblContenido1 = new javax.swing.JLabel();
        cbNotificarCorreo = new javax.swing.JCheckBox();
        cbNotificarSMS = new javax.swing.JCheckBox();
        lblContenido2 = new javax.swing.JLabel();
        txtDestinatario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enviar Mensaje Privado");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(241, 250, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo.setBackground(new java.awt.Color(255, 255, 255));
        lbltitulo.setFont(new java.awt.Font("Amarillo", 2, 24)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo.setText("Enviar Mensaje Privado");
        jPanel1.add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 350, 70));

        barra1.setBackground(new java.awt.Color(37, 161, 142));
        barra1.setOpaque(true);
        jPanel1.add(barra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 910, 60));

        barra2.setBackground(new java.awt.Color(37, 161, 142));
        barra2.setOpaque(true);
        jPanel1.add(barra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 60));

        lblContenido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContenido.setText("Para:");
        jPanel1.add(lblContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        btnEnviarMensajePrivado.setBackground(new java.awt.Color(37, 161, 142));
        btnEnviarMensajePrivado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEnviarMensajePrivado.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarMensajePrivado.setText("Enviar Mensaje Privado");
        btnEnviarMensajePrivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMensajePrivadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviarMensajePrivado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 230, 35));

        btnCancelar.setBackground(new java.awt.Color(37, 161, 142));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 210, 35));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        txtContenido.setColumns(20);
        txtContenido.setRows(5);
        txtContenido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContenidoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtContenido);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 830, 130));

        lblContenido1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblContenido1.setText("Notificación:");
        jPanel1.add(lblContenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        cbNotificarCorreo.setText("Notificar Correo");
        jPanel1.add(cbNotificarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        cbNotificarSMS.setText("Notificar SMS");
        jPanel1.add(cbNotificarSMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 110, 20));

        lblContenido2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContenido2.setText("Contenido:");
        jPanel1.add(lblContenido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        jPanel1.add(txtDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 700, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarMensajePrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMensajePrivadoActionPerformed
        comunicadorVista.consultarUsuarioPorNombre(this.txtDestinatario.getText());

    }//GEN-LAST:event_btnEnviarMensajePrivadoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        RegistrarNotificacionEvent.getInstance().desuscribirse(this);
        ConsultarUsuarioPorNombreEvent.getInstance().desuscribir(this);
        MuroFrm m = new MuroFrm(comunicadorVista, usuario);
        m.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtContenidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContenidoKeyTyped
        if (txtContenido.getText().length() == 255) {
            evt.consume();
        }
    }//GEN-LAST:event_txtContenidoKeyTyped

    public void enviarNotificacionPrivada(Usuario destinatario) {
        Calendar fecha = Calendar.getInstance();
        Notificacion notificacion= new Notificacion();
        if(this.cbNotificarCorreo.isSelected() && this.cbNotificarSMS.isSelected()){
            notificacion = new Notificacion(usuario, destinatario, fecha, MotorEnvio.ambos, this.txtContenido.getText());
        } else if (this.cbNotificarCorreo.isSelected()){
            notificacion = new Notificacion(usuario, destinatario, fecha, MotorEnvio.simpleJavaMail, this.txtContenido.getText());
        } else if (this.cbNotificarSMS.isSelected()){
            notificacion = new Notificacion(usuario, destinatario, fecha, MotorEnvio.TwilioSMS, this.txtContenido.getText());
        } 
        comunicadorVista.registrarNotificacion(notificacion);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barra1;
    private javax.swing.JLabel barra2;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviarMensajePrivado;
    private javax.swing.JCheckBox cbNotificarCorreo;
    private javax.swing.JCheckBox cbNotificarSMS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContenido;
    private javax.swing.JLabel lblContenido1;
    private javax.swing.JLabel lblContenido2;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextArea txtContenido;
    private javax.swing.JTextField txtDestinatario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onRegistrarNotificacion(PeticionNotificacion respuesta) {
        if (respuesta.getStatus() < 400) {
            JOptionPane.showMessageDialog(this, "Se registro la notificacion correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, respuesta.getMensajeError(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    @Override
    public void onConsultarUsuarioPorNombre(PeticionUsuario peticion) {
        if (peticion.getStatus() < 400) {
            System.out.println(peticion.getUsuario().getId());
            this.enviarNotificacionPrivada(peticion.getUsuario());
        } else {
            JOptionPane.showMessageDialog(this, peticion.getMensajeError(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }

}
