/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistasfacebook;

import entidades.Notificacion;
import java.text.SimpleDateFormat;

/**
 *
 * @author jegav
 */
public class NotificacionPanel extends javax.swing.JPanel {

    public Notificacion notificacion;
    
    /**
     * Creates new form NotificacionPanel
     */
    public NotificacionPanel(Notificacion notificacion) {
        initComponents();
        this.notificacion = notificacion;
        llenarPanelNotificacion();
    }
    
    public void llenarPanelNotificacion(){
        this.remitenteLbl.setText("Enviado a: "+notificacion.getDestinatario().getNombre());
        SimpleDateFormat fechaFormat = new SimpleDateFormat("dd/MM/yyyy");
        String fecha = fechaFormat.format(notificacion.getFechaCreacion().getTime());
        this.fechaLbl.setText(fecha);
        this.contenidoTxt.setText(notificacion.getContenido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        remitenteLbl = new javax.swing.JLabel();
        contenidoTxt = new javax.swing.JLabel();
        fechaLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 250, 242));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        remitenteLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        remitenteLbl.setText("Enviado a: Usuario");

        contenidoTxt.setText("ContenidoNotificacion");

        fechaLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fechaLbl.setText("29/11/2022");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenidoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(remitenteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(fechaLbl)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remitenteLbl)
                    .addComponent(fechaLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contenidoTxt;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JLabel remitenteLbl;
    // End of variables declaration//GEN-END:variables
}
